name: Build and Push to GCR
on:
  push:
    tags:
    - '*'
env:
  IMAGE: sd-bot
  REGISTRY: gcr.id

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
        
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker    
    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$REGISTRY/$PROJECT_ID/$IMAGE:${GITHUB_REF/refs\/tags\//}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$REGISTRY/$PROJECT_ID/$IMAGE:${GITHUB_REF/refs\/tags\//}"
