name: PR Validation
on:
  push:
    branches: [ main ]

jobs:
  validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Bump Version
      id: bump_version
      run: |
        npm install -g standard-version@9.1.0
        git config --global user.email "sd@bot.com"
        git config --global user.name "sd-bot"
        standard-version -t ''
        git push --follow-tags
        echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
        
    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ steps.bump_version.outputs.tag_name }}
        tag_name: ${{ steps.bump_version.outputs.tag_name }}
        body_path: CHANGELOG.md