name: PR Validation
on:
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.8

jobs:
  validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Python Version
      uses: actions/setup-python@v2
      with:
        python-version: $PYTHON_VERSION
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; pip install -r requirements.txt; fi

    - name: Test pytest
      run: |
        pytest --doctest-modules --junitxml=reports/test-results.xml --cov=./ --cov-report=xml:reports/coverage.xml --cov-config=.coveragerc

    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.3.2
      with:
        token: ${{ secrets.CODEDOV_TOKEN }}
        directory: reports
        flags: pytest
        fail_ci_if_error: false