name: Validation sd_bot
on:
  push:
    branches: [ main ]      
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '20 22 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev

    - name: Check imports with isort
      run: |
        pipenv run isort --recursive --diff .
    
    - name: Check code format with black
      run: |
        pipenv run black --check .

    - name: Check code lint with flake8
      run: |
        pipenv run flake8

    - name: Check static type with mypy
      run: |
        pipenv run mypy

    - name: Testing with pytest
      run: |
        pipenv run pytest --doctest-modules --junitxml=reports/test-results.xml --cov=./ --cov-report=xml:reports/coverage.xml --cov-config=.coveragerc --verbose

    - uses: testspace-com/setup-testspace@v1
      name: Install Testspace
      with:
        domain: hpettenuci
        token: ${{ secrets.TESTSPACE_TOKEN }}

    - name: Push result to Testspace server
      run: |
        testspace reports/*.xml

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t sd_bot:test

      - name: Smoke test docker image
        run: |
          docker run --rm -e DISCORD_TOKEN=SMOKE sd_bot:test
